- hosts: all

  vars:
    redmine_port: 8082

  tasks:
    - name: ping yc
      ansible.builtin.ping:
      tags: check

    - name: install pip
      import_role:
        name: geerlingguy.pip
      become: true
      tags: setup

    - name: install docker
      import_role:
        name: geerlingguy.docker
      become: true
      tags: setup

    - name: run redmine
      community.docker.docker_container:
        name: redmine-app
        image: redmine:latest
        state: started
        ports: "{{redmine_port}}:3000"
      become: true
      tags: redmine
