- hosts: all

  vars:
    redmine_port: 8082

  tasks:
    - name: ping yc
      ansible.builtin.ping:
      tags: check

    - name: install pip
      import_role:
        name: geerlingguy.pip
      become: true
      tags: setup

    - name: install docker
      import_role:
        name: geerlingguy.docker
      become: true
      tags: setup

    - name: create .env-file
      ansible.builtin.template:
        src: files/redmine/env.j2
        dest: .env
      tags: [deploy, setup]

    - name: run redmine
      community.docker.docker_container:
        name: redmine-app
        image: redmine:latest
        state: started
        ports: "{{redmine_port}}:3000"
        env_file: .env
      become: true
      tags: deploy
