redmine_port: 8082

datadog_api_key: "{{ datadog_api_key }}"
datadog_site: us5.datadoghq.com
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: redmine_http_check
        url: "http://localhost:{{ redmine_port }}/"
