$ANSIBLE_VAULT;1.1;AES256
38623135353232353630333734336561363537316530353732653136366234353138633532396133
3933326434326661623263646135663230386130353561610a303861373364346431346530333333
37613932656337363862613935653163306265336432353566383536386436316466633435396263
6466346431663937310a646464373733393365363563306162333037653364356466366535333638
62343633653965633833376634613738653437663830346562356266386564323966623962373733
37633064353864376661653336323039613666373237353838373634333439343132373339626335
35343664613337623563383361386434613863633932643335313039633161306161323533623461
63313062326266646262656530343533626365333139363336333566633637663839613638373066
62376530313631666331353764373831396164633263373835393732646166346237373264333930
34313333386130663461646363643531323037343139333032363761653262633863303566353039
66663337393632303931643934346165623063383533363030626665626333333337393864313833
66353836383839626262363738303733626130343234393832623233623662393762336331626166
3962
